# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190227_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('County', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.County')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='County',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.County'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Subcounty'),
        ),
    ]
